version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # also upgrade github action package versions (e.g.: actions/checkout@v4)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
